# Generated by Django 6.1.1 on 2026-09-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
