import {
  VehicleSpec,
  HyderabadHub,
  ShipmentOrder,
  FleetVehicle,
  DriverJob,
  BusinessAnalytics,
  MultiStopRoute,
} from "@/types";

export const HYDERABAD_HUBS: HyderabadHub[] = [
  { id: "hitec", name: "HITEC City", zone: "West", status: "Active", coordinates: [17.4435, 78.3772], hubType: "Tech Park", activeDrivers: 142 },
  { id: "madhapur", name: "Madhapur", zone: "West", status: "Active", coordinates: [17.4483, 78.3915], hubType: "Commercial", activeDrivers: 98 },
  { id: "gachibowli", name: "Gachibowli", zone: "West", status: "Active", coordinates: [17.4401, 78.3489], hubType: "Tech Park", activeDrivers: 110 },
  { id: "kondapur", name: "Kondapur", zone: "West", status: "Active", coordinates: [17.4699, 78.3578], hubType: "Residential", activeDrivers: 76 },
  { id: "kukatpally", name: "Kukatpally", zone: "North", status: "Active", coordinates: [17.4938, 78.4018], hubType: "Industrial", activeDrivers: 89 },
  { id: "financial-dist", name: "Financial District", zone: "West", status: "Active", coordinates: [17.4156, 78.3428], hubType: "Commercial", activeDrivers: 64 },
  { id: "nanakramguda", name: "Nanakramguda", zone: "West", status: "Active", coordinates: [17.4224, 78.3541], hubType: "Tech Park", activeDrivers: 55 },
  { id: "banjara-hills", name: "Banjara Hills", zone: "Central", status: "Active", coordinates: [17.4156, 78.4351], hubType: "Commercial", activeDrivers: 82 },
  { id: "jubilee-hills", name: "Jubilee Hills", zone: "Central", status: "Active", coordinates: [17.4319, 78.4073], hubType: "Residential", activeDrivers: 61 },
  { id: "secunderabad", name: "Secunderabad", zone: "North", status: "Active", coordinates: [17.4399, 78.4983], hubType: "Commercial", activeDrivers: 95 },
  { id: "ameerpet", name: "Ameerpet", zone: "Central", status: "Active", coordinates: [17.4375, 78.4482], hubType: "Commercial", activeDrivers: 78 },
  { id: "miyapur", name: "Miyapur", zone: "North", status: "Active", coordinates: [17.4968, 78.3546], hubType: "Industrial", activeDrivers: 45 },
  { id: "manikonda", name: "Manikonda", zone: "West", status: "Active", coordinates: [17.3984, 78.3892], hubType: "Residential", activeDrivers: 40 },
  { id: "dilsukhnagar", name: "Dilsukhnagar", zone: "East", status: "Active", coordinates: [17.3688, 78.5247], hubType: "Commercial", activeDrivers: 58 },
  { id: "uppal", name: "Uppal", zone: "East", status: "Limited", coordinates: [17.4018, 78.5602], hubType: "Industrial", activeDrivers: 32 },
  { id: "lb-nagar", name: "LB Nagar", zone: "East", status: "Limited", coordinates: [17.3457, 78.5522], hubType: "Commercial", activeDrivers: 28 },
  { id: "shamshabad", name: "Shamshabad Airport", zone: "South", status: "Active", coordinates: [17.2403, 78.4294], hubType: "Airport", activeDrivers: 49 },
];

export const VEHICLES_DATA: VehicleSpec[] = [
  {
    id: "bike",
    name: "Bike",
    tagline: "Documents & small parcels",
    capacity: "Up to 20 kg",
    dimensions: "40 x 40 x 40 cm",
    startingPrice: 99,
    baseFare: 40,
    perKmRate: 12,
    minFare: 99,
    etaMinutes: 20,
    iconName: "Bike",
    popular: true,
    evAvailable: true,
    description: "Fastest for intra-city documents, medicine, food, and small merchant parcels.",
  },
  {
    id: "auto",
    name: "Auto",
    tagline: "Great for medium goods",
    capacity: "Up to 100 kg",
    dimensions: "3.5 x 3.2 x 3.0 ft",
    startingPrice: 149,
    baseFare: 60,
    perKmRate: 16,
    minFare: 149,
    etaMinutes: 25,
    iconName: "CarFront",
    popular: true,
    evAvailable: true,
    description: "Ideal for retail store transfers, electronics, and medium carton boxes.",
  },
  {
    id: "erickshaw",
    name: "E-Rickshaw",
    tagline: "Local green deliveries",
    capacity: "Up to 250 kg",
    dimensions: "4.0 x 3.5 x 3.5 ft",
    startingPrice: 199,
    baseFare: 70,
    perKmRate: 15,
    minFare: 199,
    etaMinutes: 30,
    iconName: "Zap",
    popular: false,
    evAvailable: true,
    description: "100% zero-emission transport for neighborhood distribution and grocery bulk.",
  },
  {
    id: "tata_ace",
    name: "Tata Ace",
    tagline: "Best for bulk goods",
    capacity: "Up to 750 kg",
    dimensions: "7.0 x 4.5 x 5.0 ft",
    startingPrice: 399,
    baseFare: 200,
    perKmRate: 24,
    minFare: 399,
    etaMinutes: 35,
    iconName: "Truck",
    popular: true,
    evAvailable: true,
    description: "Hyderabad's favorite mini truck for warehouse distribution, machinery, and furniture.",
  },
  {
    id: "1ton",
    name: "1 Ton Truck",
    tagline: "Heavy commercial cargo",
    capacity: "Up to 1,200 kg",
    dimensions: "9.0 x 5.0 x 5.5 ft",
    startingPrice: 599,
    baseFare: 350,
    perKmRate: 32,
    minFare: 599,
    etaMinutes: 40,
    iconName: "Truck",
    popular: false,
    description: "Large capacity for FMCG distribution, wholesale markets, and industrial parts.",
  },
  {
    id: "2_5ton",
    name: "2-5 Ton Truck",
    tagline: "Factory & industrial shifts",
    capacity: "Up to 4,000 kg",
    dimensions: "14.0 x 6.5 x 7.0 ft",
    startingPrice: 1199,
    baseFare: 650,
    perKmRate: 48,
    minFare: 1199,
    etaMinutes: 45,
    iconName: "Container",
    popular: false,
    description: "High tonnage for manufacturing, construction materials, and inter-hub transshipment.",
  },
  {
    id: "refrigerated",
    name: "Refrigerated Van",
    tagline: "Temperature controlled (2°C - 8°C)",
    capacity: "Up to 1,500 kg",
    dimensions: "8.5 x 5.0 x 5.0 ft",
    startingPrice: 1499,
    baseFare: 850,
    perKmRate: 55,
    minFare: 1499,
    etaMinutes: 45,
    iconName: "Snowflake",
    popular: false,
    description: "Pharmaceuticals, biological samples, dairy, and cold-chain FMCG across Hyderabad.",
  },
];

export const MOCK_LIVE_ORDER: ShipmentOrder = {
  id: "ord-hyd-10482",
  trackingNumber: "HYD10482",
  pickupLocation: "Kukatpally Industrial Area, Phase 2",
  dropLocation: "Road No. 36, Jubilee Hills / Banjara Hills",
  packageType: "Machinery Spares & Retail Cartons",
  weightKg: 420,
  vehicleType: "tata_ace",
  deliveryType: "express",
  status: "IN_TRANSIT",
  estimatedFare: 685,
  driver: {
    name: "Ramesh Kumar",
    phone: "+91 98490 28412",
    rating: 4.8,
    vehicleModel: "Tata Ace EV (Army Green)",
    vehiclePlate: "TS09AB1234",
    currentLocation: "Near Madhapur Flyover",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    etaMinutes: 35,
  },
  timeline: [
    { status: "PENDING", title: "Pickup requested", timestamp: "10:22 AM", completed: true, active: false },
    { status: "DRIVER_ASSIGNED", title: "Driver assigned", timestamp: "10:26 AM", completed: true, active: false },
    { status: "DRIVER_ARRIVING", title: "Driver arriving", timestamp: "10:35 AM", completed: true, active: false },
    { status: "PICKED_UP", title: "Package picked up", timestamp: "10:42 AM", completed: true, active: false },
    { status: "IN_TRANSIT", title: "In transit", timestamp: "Live now", completed: false, active: true },
    { status: "ARRIVING", title: "Near destination", timestamp: "Est. 11:18 AM", completed: false, active: false },
    { status: "DELIVERED", title: "Delivered", timestamp: "Est. 11:25 AM", completed: false, active: false },
  ],
  proofOfDelivery: {
    deliveredAt: "10 Mar 2025 04:22 PM",
    photoUrl: "/images/pod-box.jpg",
    signatureUrl: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='140' height='60'><path d='M10 40 Q 30 10, 60 30 T 110 20 T 130 45' stroke='%2334452A' stroke-width='2.5' fill='none'/></svg>",
    gpsCoordinates: "17.4325° N, 78.4071° E (Kondapur / Banjara Hub)",
    recipientName: "Venkatesh Rao (Store Manager)",
    otpVerified: true,
  },
  createdAt: "2026-09-06T10:20:00Z",
};

export const MOCK_MULTI_STOP_ROUTE: MultiStopRoute = {
  id: "route-ms-01",
  totalDistanceKm: 54,
  estimatedDuration: "3 hr 45 min",
  estimatedCost: 1850,
  optimized: true,
  stops: [
    { id: "1", name: "Kukatpally Warehouse", area: "Pickup Hub, Phase 1", coordinates: [17.4938, 78.4018], type: "pickup", orderSequence: 1, status: "completed", contactPerson: "Satish (Lead Dispatch)" },
    { id: "2", name: "Madhapur", area: "100ft Road Retail Store", coordinates: [17.4483, 78.3915], type: "drop", orderSequence: 2, status: "completed", contactPerson: "Deepak (Manager)" },
    { id: "3", name: "Kondapur", area: "Raghava Pride Mart", coordinates: [17.4699, 78.3578], type: "drop", orderSequence: 3, status: "in-transit", contactPerson: "Sunita Reddy" },
    { id: "4", name: "Gachibowli", area: "DLF Cybercity Depot", coordinates: [17.4401, 78.3489], type: "drop", orderSequence: 4, status: "pending", contactPerson: "Praveen Kumar" },
    { id: "5", name: "Nanakramguda", area: "WaveRock Tech Park", coordinates: [17.4224, 78.3541], type: "drop", orderSequence: 5, status: "pending", contactPerson: "Ananya Sen" },
    { id: "6", name: "Financial District", area: "Amazon Tower Terminal", coordinates: [17.4156, 78.3428], type: "drop", orderSequence: 6, status: "pending", contactPerson: "Srikanth M" },
  ],
};

export const MOCK_FLEET_VEHICLES: FleetVehicle[] = [
  { id: "v1", plateNumber: "HY09AB1234", vehicleType: "Tata Ace EV", driverName: "Suresh", status: "Available", todayTrips: 4, batteryOrFuel: "88% EV", lastLocation: "Kukatpally Hub" },
  { id: "v2", plateNumber: "HY09CD4567", vehicleType: "Tata Ace Diesel", driverName: "Raju", status: "Busy", todayTrips: 6, batteryOrFuel: "65% Fuel", lastLocation: "Madhapur Metro" },
  { id: "v3", plateNumber: "TS08EF7890", vehicleType: "Auto Cargo", driverName: "Imran", status: "Available", todayTrips: 5, batteryOrFuel: "92% CNG", lastLocation: "Ameerpet Station" },
  { id: "v4", plateNumber: "TS09GH1234", vehicleType: "Electric Bike", driverName: "Naveen", status: "Maintenance", todayTrips: 0, batteryOrFuel: "Service Bay", lastLocation: "Secunderabad Workshop" },
  { id: "v5", plateNumber: "TS07JK5678", vehicleType: "1 Ton Truck", driverName: "Arjun Rao", status: "Available", todayTrips: 3, batteryOrFuel: "74% Diesel", lastLocation: "Uppal Ring Road" },
  { id: "v6", plateNumber: "TS09LM9012", vehicleType: "2-5 Ton Container", driverName: "Govind", status: "Busy", todayTrips: 2, batteryOrFuel: "81% Diesel", lastLocation: "Shamshabad Cargo" },
];

export const MOCK_DRIVER_JOBS: DriverJob[] = [
  { id: "job-1", pickup: "HITEC City (Cyber Towers)", pickupTime: "10:00 AM", drop: "Banjara Hills, Rd 12", distanceKm: 12, earnings: 120, status: "available" },
  { id: "job-2", pickup: "Kukatpally Metro", pickupTime: "11:30 AM", drop: "Madhapur D-Mart", distanceKm: 18, earnings: 180, status: "available" },
  { id: "job-3", pickup: "Ameerpet Junction", pickupTime: "02:00 PM", drop: "Secunderabad Clock Tower", distanceKm: 14, earnings: 110, status: "available" },
  { id: "job-4", pickup: "Gachibowli Stadium", pickupTime: "03:45 PM", drop: "Financial District", distanceKm: 8, earnings: 95, status: "available" },
];

export const MOCK_BUSINESS_ANALYTICS: BusinessAnalytics = {
  todayOrders: 128,
  deliveredOrders: 96,
  inTransitOrders: 24,
  failedOrders: 8,
  totalDistanceKm: 487,
  deliveryCost: 18240,
  codCollected: 142000,
  successRate: 94,
  ordersTrend: [
    { time: "8 AM", orders: 12, delivered: 10 },
    { time: "10 AM", orders: 28, delivered: 22 },
    { time: "12 PM", orders: 42, delivered: 34 },
    { time: "2 PM", orders: 31, delivered: 26 },
    { time: "4 PM", orders: 58, delivered: 46 },
    { time: "6 PM", orders: 46, delivered: 39 },
    { time: "8 PM", orders: 24, delivered: 21 },
  ],
  vehicleUtilization: [
    { name: "Tata Ace", percentage: 29, fill: "#34452A" },
    { name: "Bike", percentage: 24, fill: "#59663A" },
    { name: "Auto", percentage: 22, fill: "#B5A477" },
    { name: "Trucks", percentage: 16, fill: "#25351F" },
    { name: "EV Rickshaw", percentage: 9, fill: "#74776E" },
  ],
};
